# Generated by Django 3.1.5 on 2021-03-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_title_kg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='title_kg',
            new_name='title_ky',
        ),
    ]
