# Generated by Django 3.1.5 on 2021-03-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210315_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_af',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ar_dz',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ast',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_az',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_be',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_bg',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_bn',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_br',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_bs',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ca',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_cs',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_cy',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_da',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_de',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_dsb',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_el',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_au',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en_gb',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_eo',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_ar',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_co',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_mx',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_ni',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es_ve',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_et',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_eu',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fa',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fi',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_fy',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ga',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_gd',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_gl',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_he',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hi',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hsb',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hu',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_hy',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ia',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ig',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ind',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_io',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_is',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_it',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ja',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ka',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kab',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_km',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kn',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ko',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ky',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_lb',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_lt',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_lv',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_mk',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ml',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_mn',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_mr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_my',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nb',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ne',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nl',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nn',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_os',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pa',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pl',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pt',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pt_br',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ro',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sk',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sl',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sq',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sr_latn',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sv',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_sw',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ta',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_te',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tg',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_th',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tk',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_tt',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_udm',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ur',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_vi',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_hans',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_hant',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_af',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar_dz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ast',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_az',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_be',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_bg',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_bn',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_br',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_bs',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ca',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_cs',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_cy',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_da',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_dsb',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_el',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en_au',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en_gb',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_eo',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es_ar',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es_co',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es_mx',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es_ni',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_es_ve',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_et',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_eu',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fi',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_fy',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ga',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_gd',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_gl',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_he',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hi',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hsb',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hu',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_hy',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ia',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ig',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ind',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_io',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_is',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_it',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ja',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ka',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_kab',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_km',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_kn',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ko',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_lb',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_lt',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_lv',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_mk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ml',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_mn',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_mr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_my',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_nb',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ne',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_nl',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_nn',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_os',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pa',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pl',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pt',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_pt_br',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ro',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sl',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sq',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sr_latn',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sv',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_sw',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ta',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_te',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tg',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_th',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_tt',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_udm',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ur',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_vi',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_zh_hans',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_zh_hant',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_af',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ar_dz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ast',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_be',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_bg',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_bn',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_bs',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ca',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_cs',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_cy',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_da',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_de',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_dsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_el',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en_au',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_en_gb',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_eo',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_es_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_es_co',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_es_mx',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_es_ni',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_es_ve',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_et',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_eu',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fa',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fi',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_fy',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ga',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_gd',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_gl',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_he',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_hi',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_hr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_hsb',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_hu',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_hy',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ia',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ig',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ind',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_io',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_is',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_it',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ja',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ka',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_kab',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_kk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_km',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_kn',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ko',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_lb',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_lt',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_lv',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_mk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ml',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_mn',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_mr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_my',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_nb',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ne',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_nl',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_nn',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_os',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_pa',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_pl',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_pt',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_pt_br',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ro',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_sk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_sl',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_sq',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_sr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_sr_latn',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_sv',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ta',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_te',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tg',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_th',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_tt',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_udm',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uk',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ur',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_vi',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_zh_hans',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
