# Generated by Django 3.1.5 on 2021-03-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210315_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_kg',
            new_name='name_ky',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description_kg',
            new_name='description_ky',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_kg',
            new_name='title_ky',
        ),
    ]
