# Generated by Django 3.1.5 on 2021-03-16 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210315_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ')),
                ('key_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ')),
                ('key_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ')),
                ('key_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('value_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('value_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('value_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Значение')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name_plural': 'Технические данные',
                'ordering': ['-id'],
            },
        ),
    ]
