# Generated by Django 3.1.5 on 2021-03-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210315_1452'),
        ('product', '0009_auto_20210315_1423'),
    ]

    operations = [
    ]
