# Generated by Django 3.1.5 on 2021-03-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20210316_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='application_area',
            field=models.TextField(blank=True, null=True, verbose_name='Область применения'),
        ),
        migrations.AddField(
            model_name='product',
            name='application_area_en',
            field=models.TextField(blank=True, null=True, verbose_name='Область применения'),
        ),
        migrations.AddField(
            model_name='product',
            name='application_area_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Область применения'),
        ),
        migrations.AddField(
            model_name='product',
            name='application_area_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Область применения'),
        ),
    ]
