# Generated by Django 3.1.5 on 2021-03-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210316_0748'),
        ('product', '0011_merge_20210315_1512'),
    ]

    operations = [
    ]
