# Generated by Django 3.1.5 on 2021-03-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210315_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description_kg',
            new_name='description_ky',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title_kg',
            new_name='title_ky',
        ),
    ]
