# Generated by Django 3.1.5 on 2021-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ФИО')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Почта')),
                ('comment', models.CharField(blank=True, max_length=650, null=True, verbose_name='Комментарии')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
