# Generated by Django 3.1.5 on 2021-03-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formemail',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Сообщение (комментарий)'),
        ),
        migrations.AlterField(
            model_name='formemail',
            name='number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Номер телефона'),
        ),
    ]
